const s = require('./api/config/server')
const routerMW = require('./api/routes/routesMW')
const routerXML = require('./api/routes/routesXML')
const routerOPT = require('./api/routes/routesOPT')
const routerVoice = require('./api/routes/routesVoice')
const routerUCI = require('./api/routes/routesUCI')
s.server.use('/MWAIDA', routerMW)
s.server.use('/XML', routerXML)
s.server.use('/OPT', routerOPT)
s.server.use('/Voice', routerVoice)
s.server.use('/UCI', routerUCI)